### ISSUE TITLE
Code examples for DKAN Migrate Base

### ISSUE THREAD

**Issue by Forester1** [NuCivic/dkan_migrate_base#3]
Hi

Thanks for doing this.

We're looking at using something like this for our open data portal:
http://opendata.cambridgeshireinsight.org.uk/

but could really use some code examples to help us get it up and running.

All help appreciated

**Comment by acouch** [comment]
Thanks for asking. We will try and provide something as soon as we are able.

**Comment by Forester1** [comment]
Great.  Thanks for getting back to us.

**Comment by acouch** [comment]
We have just improved the ability to make this extensible https://github.com/NuCivic/dkan_migrate_base/pull/4 . We are working on providing some better documentation and code examples. Thanks for your patience!

**Comment by acouch** [comment]
We've created some code examples: https://github.com/NuCivic/dkan_migrate_base/tree/master/modules/dkan_migrate_base_example

This creates an example module that inherits the base migration classes. The Dataset and Resource migrations run separately. All you have to do is change the endpoints for the Dataset and Resource migrations here: https://github.com/NuCivic/dkan_migrate_base/blob/master/modules/dkan_migrate_base_example/dkan_migrate_base_example.module#L41

Please PM us if you want to share the instance you are trying to migrate and we will test it ourselves.
